
players:
  played-in-unknown-state: false
  afk-minutes: 5  # todo

database:
  mysql:
    username: root
    password: "password"
    address: localhost:3306
    database: "bungeeplaytime"
    options:
      autoReconnect: true
