
players:
  played-in-unknown-state: false
  afk-minutes: 5

db-type: mysql
# available: mysql, sqlite

database:
  mysql:
    username: root
    password: "password"
    address: localhost:3306
    database: "bungeeplaytime"
    options:
      autoReconnect: true

  sqlite:
    address: database.db
    options:

# Use ConnectorPlugin in API communication
enable-connector-plugin-support: true
